FROM rayproject/ray:2.46.0-py311-gpu

USER root

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ray-train/requirements.txt .
COPY ray-train/densenet.py .
COPY ray-train/utils.py .

CMD ["python", "densenet.py"]