# kubectl apply -f train-manifest.yaml -n ray-train
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-cell-densenet
spec:
  entrypoint: python densenet.py
  shutdownAfterJobFinishes: true
  rayClusterSpec:
    rayVersion: "2.46.0"
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:        
        spec:
          serviceAccountName: ray-ksa
          containers:
            - name: ray-head
              image: us-central1-docker.pkg.dev/the-haem-dream/haem-artifacts/cell-train@sha256:e42160e71a838064e6f279a2b5a398850b6279af6fb1315f48b059763bb2a858
              env:
                  - name: MLFLOW_TRACKING_URI
                    value: "http://mlflow.mlflow.svc.cluster.local:5000"
                  - name: BATCH_SIZE
                    value: "16"
                  - name: EPOCHS
                    value: "10"
                  - name: TRAIN_LEARNING_RATE
                    value: "0.001"
                  - name: TRUNCATE_DATASET
                    value: "True"    
                  - name: TRAIN_NUM_WORKERS
                    value: "1"
              resources:
                requests:
                  cpu: "2"
                  memory: "16Gi"
                  ephemeral-storage: "8Gi"
                limits:
                  ephemeral-storage: "8Gi"
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        groupName: training-workers
        template:
          spec:
            serviceAccountName: ray-ksa
            containers:
              - name: ray-worker
                image: us-central1-docker.pkg.dev/the-haem-dream/haem-artifacts/cell-train@sha256:e42160e71a838064e6f279a2b5a398850b6279af6fb1315f48b059763bb2a858
                resources:
                  requests:
                    cpu: "4"
                    memory: "16Gi"
                    ephemeral-storage: "8Gi"
            #        nvidia.com/gpu: 1
                  limits:
                    ephemeral-storage: "8Gi"
            #        nvidia.com/gpu: 1
            #nodeSelector:
              #cloud.google.com/compute-class: Accelerator
              #cloud.google.com/gke-accelerator: nvidia-l4

                          