[project]
name = "the-haem-dream"
version = "0.1.2"
description = "A cloud-native project for detecting anamolous cells in a blood film."
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
ui = ["streamlit", "fastapi", "uvicorn"]
training = ["torch", "torchvision", "ray[data,train]", "google-cloud-storage", "fsspec[full]", "mlflow-skinny"]

[tool.uv]
package = true