[project]
name = "the-haem-dream"
version = "1.0.0"
description = "A cloud-native project for detecting anamolous cells in a blood film."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ray[serve]>=2.55.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.extra-build-dependencies]
the-haem-dream = ["setuptools"]

[project.optional-dependencies]
ui = ["streamlit", "fastapi", "uvicorn"]
training = ["torch", "torchvision", "ray[data,train]", "google-cloud-storage", "fsspec[full]", "mlflow-skinny"]

[tool.uv]
package = true
