[project]
name = "the-haem-dream"
version = "0.1.0"
description = "A cloud-native project for detecting anamolous cells in a blood film."
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
ui = ["streamlit>=1.57.0", "fastapi>=0.136.1", "uvicorn>=0.46.0"]
training = ["torch>=2.11.0", "torchvision>=0.26.0", "ray[data,train]>=2.55.1", "google-cloud-storage", "fsspec[full]"]

[tool.uv]
package = true