FROM rayproject/ray:2.46.0-py311-gpu

USER root

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir setuptools uv && uv sync --no-cache --extra training

CMD ["uv", "run", "python", "-m", "the_haem_dream.training.densenet"]