FROM rayproject/ray:2.46.0-py311-gpu

USER root

WORKDIR /app


COPY ray-serve/requirements.txt .
COPY ray-serve/serve-cell-detector.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "serve-cell-detector.py"]