apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui
  namespace: prod
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: streamlit-ui
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      containers:
      - name: streamlit-ui
        image: IMAGE
        ports:
          - containerPort: 8501
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60