FROM python:3.11-slim

WORKDIR /app

COPY ui/requirements.txt .
COPY ui/st-app.py .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["streamlit", "run", "st-app.py", "--server.port=8080", "--server.address=0.0.0.0", "--server.enableXsrfProtection=false", "--server.enableCORS=false"]